#include "Game/Actor/aiQueryFactories.h"
#include <array>
#include "Game/Actor/Query/queryBranchByDyeColor.h"
#include "Game/Actor/Query/queryBranchByGameOver.h"
#include "Game/Actor/Query/queryCanCreateMakeItemList.h"
#include "Game/Actor/Query/queryCanMarkMapPin.h"
#include "Game/Actor/Query/queryCheck100EnemyActiveTiming.h"
#include "Game/Actor/Query/queryCheckActorAction.h"
#include "Game/Actor/Query/queryCheckActorAction13.h"
#include "Game/Actor/Query/queryCheckActorAction14_2.h"
#include "Game/Actor/Query/queryCheckAddPorchItem.h"
#include "Game/Actor/Query/queryCheckAppPoint.h"
#include "Game/Actor/Query/queryCheckAppShopSelect.h"
#include "Game/Actor/Query/queryCheckAreaTransition.h"
#include "Game/Actor/Query/queryCheckBalladOfHeroActiveTiming.h"
#include "Game/Actor/Query/queryCheckContainerItem.h"
#include "Game/Actor/Query/queryCheckCookResultStatus.h"
#include "Game/Actor/Query/queryCheckCurrentMap.h"
#include "Game/Actor/Query/queryCheckCurseRRetryEverOnce.h"
#include "Game/Actor/Query/queryCheckDeadHorseResistered.h"
#include "Game/Actor/Query/queryCheckDeadlyQuestEscapeTiming.h"
#include "Game/Actor/Query/queryCheckDieCnt.h"
#include "Game/Actor/Query/queryCheckDistanceForWarp.h"
#include "Game/Actor/Query/queryCheckDistanceFromPlayer.h"
#include "Game/Actor/Query/queryCheckDownloadItemNum.h"
#include "Game/Actor/Query/queryCheckDuringBloodyMoon.h"
#include "Game/Actor/Query/queryCheckDyeShopSelect.h"
#include "Game/Actor/Query/queryCheckE3Mode.h"
#include "Game/Actor/Query/queryCheckEatActor.h"
#include "Game/Actor/Query/queryCheckElapsedTimeOfMiniGame.h"
#include "Game/Actor/Query/queryCheckEquipArmorSeriesType.h"
#include "Game/Actor/Query/queryCheckEquipItemType.h"
#include "Game/Actor/Query/queryCheckEquipment.h"
#include "Game/Actor/Query/queryCheckExistActor.h"
#include "Game/Actor/Query/queryCheckExistArrow.h"
#include "Game/Actor/Query/queryCheckExtraEnergyOfPlayer.h"
#include "Game/Actor/Query/queryCheckExtraLifeOfPlayer.h"
#include "Game/Actor/Query/queryCheckFadeState.h"
#include "Game/Actor/Query/queryCheckFame.h"
#include "Game/Actor/Query/queryCheckFlag.h"
#include "Game/Actor/Query/queryCheckGameDataFloat.h"
#include "Game/Actor/Query/queryCheckGameDataInt.h"
#include "Game/Actor/Query/queryCheckGetDemoTypeFromArg.h"
#include "Game/Actor/Query/queryCheckGiveReward.h"
#include "Game/Actor/Query/queryCheckHasManifactureArmor.h"
#include "Game/Actor/Query/queryCheckHorseCustomizeSelect.h"
#include "Game/Actor/Query/queryCheckHorseDeadCause.h"
#include "Game/Actor/Query/queryCheckHorseRegistered.h"
#include "Game/Actor/Query/queryCheckHorseTakenOut.h"
#include "Game/Actor/Query/queryCheckIsOpenItemCategory.h"
#include "Game/Actor/Query/queryCheckItemShopDecide.h"
#include "Game/Actor/Query/queryCheckItemShopPorchVacancy.h"
#include "Game/Actor/Query/queryCheckItemShopSelect.h"
#include "Game/Actor/Query/queryCheckItemShopSelectBuy.h"
#include "Game/Actor/Query/queryCheckLastDamageAttacker.h"
#include "Game/Actor/Query/queryCheckManufactResult.h"
#include "Game/Actor/Query/queryCheckMapArea.h"
#include "Game/Actor/Query/queryCheckMasterSwordState.h"
#include "Game/Actor/Query/queryCheckMaterialValue.h"
#include "Game/Actor/Query/queryCheckMiniGameTime.h"
#include "Game/Actor/Query/queryCheckMiniGameTimeOver.h"
#include "Game/Actor/Query/queryCheckNumOfBuyPicture.h"
#include "Game/Actor/Query/queryCheckOwnedHorseFamiliarity.h"
#include "Game/Actor/Query/queryCheckPictureBookVacancy.h"
#include "Game/Actor/Query/queryCheckPlacedItemSaled.h"
#include "Game/Actor/Query/queryCheckPlayerDeadCause.h"
#include "Game/Actor/Query/queryCheckPlayerEquip.h"
#include "Game/Actor/Query/queryCheckPlayerFastFadeDead.h"
#include "Game/Actor/Query/queryCheckPlayerHellType.h"
#include "Game/Actor/Query/queryCheckPlayerPullSwordFailEnd.h"
#include "Game/Actor/Query/queryCheckPlayerRideHorse.h"
#include "Game/Actor/Query/queryCheckPlayerRideSunazarashi.h"
#include "Game/Actor/Query/queryCheckPlayerState.h"
#include "Game/Actor/Query/queryCheckPlayerTemperatureCondition.h"
#include "Game/Actor/Query/queryCheckPlayerWeaponFired.h"
#include "Game/Actor/Query/queryCheckPorchInItem.h"
#include "Game/Actor/Query/queryCheckProConUse.h"
#include "Game/Actor/Query/queryCheckRainRatio.h"
#include "Game/Actor/Query/queryCheckRankOfEnemyAttackedNPC.h"
#include "Game/Actor/Query/queryCheckReceiveTerrorLevel.h"
#include "Game/Actor/Query/queryCheckResultOfNPCConflict.h"
#include "Game/Actor/Query/queryCheckRoad.h"
#include "Game/Actor/Query/queryCheckRupee.h"
#include "Game/Actor/Query/queryCheckSelectPicture.h"
#include "Game/Actor/Query/queryCheckSellResult.h"
#include "Game/Actor/Query/queryCheckShopSelectedItemName.h"
#include "Game/Actor/Query/queryCheckSiteBossDamageAnm.h"
#include "Game/Actor/Query/queryCheckStage.h"
#include "Game/Actor/Query/queryCheckStarter.h"
#include "Game/Actor/Query/queryCheckTerrorLevel.h"
#include "Game/Actor/Query/queryCheckTime.h"
#include "Game/Actor/Query/queryCheckTimeType.h"
#include "Game/Actor/Query/queryCheckTypeOfOwnedHorseForEvent.h"
#include "Game/Actor/Query/queryCheckTypeOfWildHorseAssociated.h"
#include "Game/Actor/Query/queryCheckVacancyItem.h"
#include "Game/Actor/Query/queryCheckWarpMist.h"
#include "Game/Actor/Query/queryCheckWeaponVacancyItem.h"
#include "Game/Actor/Query/queryCheckWeather.h"
#include "Game/Actor/Query/queryCompareGameDataFloat.h"
#include "Game/Actor/Query/queryCompareGameDataInt.h"
#include "Game/Actor/Query/queryCompareGameDataTime.h"
#include "Game/Actor/Query/queryComparePlayerFireResistantLevel.h"
#include "Game/Actor/Query/queryComparePlayerHeart.h"
#include "Game/Actor/Query/queryComparePlayerMaxHeart.h"
#include "Game/Actor/Query/queryComparePlayerMaxStamina.h"
#include "Game/Actor/Query/queryComparePlayerOriginalHeart.h"
#include "Game/Actor/Query/queryCountFlag4.h"
#include "Game/Actor/Query/queryEnemyDieCheck.h"
#include "Game/Actor/Query/queryEnemyRestLifeRate.h"
#include "Game/Actor/Query/queryGeneralChoice2.h"
#include "Game/Actor/Query/queryGeneralChoice3.h"
#include "Game/Actor/Query/queryGeneralChoice4.h"
#include "Game/Actor/Query/queryGeneralChoice8.h"
#include "Game/Actor/Query/queryHasArmorAlreadyDyed.h"
#include "Game/Actor/Query/queryHasArmorDye.h"
#include "Game/Actor/Query/queryHasCookResultInPorch.h"
#include "Game/Actor/Query/queryHasEnoughPayment.h"
#include "Game/Actor/Query/queryHasItemDye.h"
#include "Game/Actor/Query/queryHasItemDyeSpecifiedColor.h"
#include "Game/Actor/Query/queryHasPorchArrow.h"
#include "Game/Actor/Query/queryHasPorchItem.h"
#include "Game/Actor/Query/queryHasPorchItemByCategory.h"
#include "Game/Actor/Query/queryHasPouchItemByPouchCategory.h"
#include "Game/Actor/Query/queryHasSetItem.h"
#include "Game/Actor/Query/queryHasSpecificArmorSeries.h"
#include "Game/Actor/Query/queryIsAppAlreadyExchanged.h"
#include "Game/Actor/Query/queryIsArriveAnchorForRain.h"
#include "Game/Actor/Query/queryIsAwakened.h"
#include "Game/Actor/Query/queryIsBloodyMoonTrig.h"
#include "Game/Actor/Query/queryIsCurrentAocFieldStage.h"
#include "Game/Actor/Query/queryIsCurrentCDungeonStage.h"
#include "Game/Actor/Query/queryIsCurrentMainFieldDungeonStage.h"
#include "Game/Actor/Query/queryIsCurrentMainFieldStage.h"
#include "Game/Actor/Query/queryIsEquipedDyedArmor.h"
#include "Game/Actor/Query/queryIsEquippedEnableDye.h"
#include "Game/Actor/Query/queryIsEquippedWithLowerBody.h"
#include "Game/Actor/Query/queryIsHorseFamiliarityPassedAlready.h"
#include "Game/Actor/Query/queryIsHorseNumMax.h"
#include "Game/Actor/Query/queryIsIgnitionByArrowFire.h"
#include "Game/Actor/Query/queryIsItemInStock.h"
#include "Game/Actor/Query/queryIsNeedEquipWeapon.h"
#include "Game/Actor/Query/queryIsNoEquipArmorAnyTarget.h"
#include "Game/Actor/Query/queryIsOffLinkTag.h"
#include "Game/Actor/Query/queryIsOnEnterDungeonFlag.h"
#include "Game/Actor/Query/queryIsOnInstEventFlag.h"
#include "Game/Actor/Query/queryIsOwnedHorseAssociated.h"
#include "Game/Actor/Query/queryIsPlayerGrounded.h"
#include "Game/Actor/Query/queryIsRest.h"
#include "Game/Actor/Query/queryIsRideHorse.h"
#include "Game/Actor/Query/queryIsSoldOut.h"
#include "Game/Actor/Query/queryIsSuccessEndLastDemoAction.h"
#include "Game/Actor/Query/queryIsTerrorDisappeared.h"
#include "Game/Actor/Query/queryIsWeaponDrawn.h"
#include "Game/Actor/Query/queryKeyInputCheck.h"
#include "Game/Actor/Query/queryRandomChoice2.h"
#include "Game/Actor/Query/queryRandomChoice3.h"
#include "Game/Actor/Query/queryRandomChoice4.h"
#include "Game/Actor/Query/queryRandomChoice8.h"
#include "Game/Actor/Query/queryRandomChoiceExceptOnFlag.h"
#include "Game/Actor/Query/queryWhatCurrentItem.h"
#include "Game/Actor/Query/queryWhatDayOfTheWeek.h"
#include "Game/Actor/Query/queryWhatDungeonType.h"
#include "Game/Actor/Query/queryWhatMoonName.h"
#include "KingSystem/ActorSystem/actAiQueries.h"
#include "KingSystem/ActorSystem/actAiQuery.h"
#include "KingSystem/ActorSystem/queryCheckEventCancel.h"
#include "KingSystem/ActorSystem/queryCheckJustBeforeEventCancel.h"
#include "KingSystem/ActorSystem/queryDummyQuery.h"
#include "KingSystem/ActorSystem/queryIsWaitRevival.h"

namespace uking {

using Factory = ksys::act::ai::QueryFactory;

static ksys::act::ai::QueryFactory sQueryFactories[] = {
    {0x00f284eb, Factory::make<query::CheckDeadHorseResistered>},
    {0x011adade, Factory::make<query::IsEquipedDyedArmor>},
    {0x01537944, Factory::make<query::CheckHasManifactureArmor>},
    {0x0a457b63, Factory::make<query::IsRideHorse>},
    {0x0b84de7f, Factory::make<query::CheckHorseTakenOut>},
    {0x104fa725, Factory::make<query::CheckShopSelectedItemName>},
    {0x10f6317c, Factory::make<query::CheckPictureBookVacancy>},
    {0x1114b11c, Factory::make<query::CheckSelectPicture>},
    {0x111b1ea5, Factory::make<query::RandomChoiceExceptOnFlag>},
    {0x119d690c, Factory::make<query::CanCreateMakeItemList>},
    {0x13601638, Factory::make<query::CheckProConUse>},
    {0x1491e6db, Factory::make<query::CheckHorseCustomizeSelect>},
    {0x14a31adf, Factory::make<query::CompareGameDataInt>},
    {0x15995510, Factory::make<query::CheckItemShopPorchVacancy>},
    {0x179f2f26, Factory::make<query::CheckWeather>},
    {0x18aad679, Factory::make<query::CheckMaterialValue>},
    {0x18c87da4, Factory::make<query::CheckCurrentMap>},
    {0x19d08c2a, Factory::make<query::GeneralChoice3>},
    {0x1a02a525, Factory::make<query::CheckCurseRRetryEverOnce>},
    {0x1b0ddfc3, Factory::make<query::CheckStarter>},
    {0x1f3fdfc6, Factory::make<query::IsEquippedEnableDye>},
    {0x21171d40, Factory::make<query::CheckPlayerWeaponFired>},
    {0x242a4eea, Factory::make<query::CheckGameDataFloat>},
    {0x26f46b0d, Factory::make<query::CheckEquipItemType>},
    {0x273e5dee, Factory::make<query::IsSuccessEndLastDemoAction>},
    {0x2754bd6c, Factory::make<query::CheckRankOfEnemyAttackedNPC>},
    {0x279054bd, Factory::make<query::CheckHorseRegistered>},
    {0x2e7d60bc, Factory::make<query::CheckTypeOfOwnedHorseForEvent>},
    {0x2f7e3c79, Factory::make<query::KeyInputCheck>},
    {0x3200fcb3, Factory::make<query::IsCurrentAocFieldStage>},
    {0x3293c243, Factory::make<query::IsPlayerGrounded>},
    {0x329453e0, Factory::make<query::CheckPlacedItemSaled>},
    {0x383c25ee, Factory::make<query::WhatDayOfTheWeek>},
    {0x39a8f9ac, Factory::make<query::CheckDyeShopSelect>},
    {0x3f91ea1a, Factory::make<query::IsEquippedWithLowerBody>},
    {0x40da7f69, Factory::make<query::CheckMapArea>},
    {0x4563a203, Factory::make<query::IsOffLinkTag>},
    {0x466ffb31, Factory::make<query::CheckDuringBloodyMoon>},
    {0x479f4be0, Factory::make<query::IsWeaponDrawn>},
    {0x47c59074, Factory::make<query::CheckMasterSwordState>},
    {0x4b19f284, Factory::make<query::IsAppAlreadyExchanged>},
    {0x4b9c4380, Factory::make<query::CheckGiveReward>},
    {0x52edf76e, Factory::make<query::IsBloodyMoonTrig>},
    {0x541025b5, Factory::make<query::CheckWarpMist>},
    {0x55f620ef, Factory::make<query::CheckTime>},
    {0x56330fc5, Factory::make<query::CheckAppPoint>},
    {0x593aeafb, Factory::make<query::CheckDistanceForWarp>},
    {0x5a267486, Factory::make<query::CheckMiniGameTime>},
    {0x5b8531ea, Factory::make<query::IsRest>},
    {0x5e0930ab, Factory::make<query::CountFlag4>},
    {0x5e30f736, Factory::make<query::CheckHorseDeadCause>},
    {0x5e4b5e37, Factory::make<query::CheckRupee>},
    {0x5f35aa5a, Factory::make<query::CheckGameDataInt>},
    {0x5f93f5f6, Factory::make<query::CheckEquipment>},
    {0x6013e082, Factory::make<ksys::act::ai::DummyQuery>},
    {0x63148c7e, Factory::make<query::ComparePlayerFireResistantLevel>},
    {0x6593295f, Factory::make<ksys::act::ai::IsWaitRevival>},
    {0x668f18a7, Factory::make<query::CheckAppShopSelect>},
    {0x67f56d1d, Factory::make<query::CheckSiteBossDamageAnm>},
    {0x692f3d2e, Factory::make<query::CheckDeadlyQuestEscapeTiming>},
    {0x695ba369, Factory::make<query::HasPorchArrow>},
    {0x69850566, Factory::make<query::IsNoEquipArmorAnyTarget>},
    {0x69e3a6cc, Factory::make<query::CheckPlayerTemperatureCondition>},
    {0x6a28f65c, Factory::make<query::HasItemDye>},
    {0x6a65ae75, Factory::make<query::HasEnoughPayment>},
    {0x6ad7618a, Factory::make<query::ComparePlayerOriginalHeart>},
    {0x6be9ad36, Factory::make<query::CheckPlayerRideSunazarashi>},
    {0x6cfae748, Factory::make<query::CheckVacancyItem>},
    {0x6ed7bcbc, Factory::make<query::GeneralChoice2>},
    {0x71deee37, Factory::make<query::RandomChoice8>},
    {0x743f140f, Factory::make<query::CheckPorchInItem>},
    {0x749d8ed7, Factory::make<query::CheckPlayerDeadCause>},
    {0x74a44ed1, Factory::make<query::CheckEquipArmorSeriesType>},
    {0x7804223d, Factory::make<query::CheckExtraLifeOfPlayer>},
    {0x78536534, Factory::make<query::IsOwnedHorseAssociated>},
    {0x7868a21c, Factory::make<query::RandomChoice4>},
    {0x78bf5625, Factory::make<query::HasPorchItem>},
    {0x798799cb, Factory::make<query::IsCurrentCDungeonStage>},
    {0x7b91718e, Factory::make<query::CheckEatActor>},
    {0x7ca25d9f, Factory::make<query::ComparePlayerHeart>},
    {0x7edd580d, Factory::make<query::CheckExistActor>},
    {0x7f950ed0, Factory::make<query::CheckGetDemoTypeFromArg>},
    {0x7fe578d7, Factory::make<query::CheckRainRatio>},
    {0x8021dd19, Factory::make<query::CheckPlayerFastFadeDead>},
    {0x811c21e6, Factory::make<query::CheckBalladOfHeroActiveTiming>},
    {0x85d86eb1, Factory::make<query::WhatMoonName>},
    {0x87b41989, Factory::make<query::GeneralChoice4>},
    {0x87faaf7c, Factory::make<query::CheckActorAction>},
    {0x88949f2a, Factory::make<query::CheckE3Mode>},
    {0x8a6f4de8, Factory::make<query::HasCookResultInPorch>},
    {0x8c3dea42, Factory::make<query::CheckDownloadItemNum>},
    {0x8e0255a2, Factory::make<query::GeneralChoice8>},
    {0x90477720, Factory::make<query::BranchByDyeColor>},
    {0x910b0729, Factory::make<query::RandomChoice2>},
    {0x979ded52, Factory::make<query::CheckDistanceFromPlayer>},
    {0x98297948, Factory::make<query::HasArmorAlreadyDyed>},
    {0x988da1f6, Factory::make<query::IsHorseNumMax>},
    {0x98934f65, Factory::make<ksys::act::ai::CheckJustBeforeEventCancel>},
    {0x9909e013, Factory::make<query::CheckIsOpenItemCategory>},
    {0x9a1ef0c2, Factory::make<query::CheckNumOfBuyPicture>},
    {0x9f439257, Factory::make<query::WhatCurrentItem>},
    {0xa1f5ee43, Factory::make<query::CheckFame>},
    {0xa3479bb1, Factory::make<query::BranchByGameOver>},
    {0xa5abed4c, Factory::make<query::CheckPlayerEquip>},
    {0xa6b54a76, Factory::make<query::CheckSellResult>},
    {0xa6f521c1, Factory::make<query::ComparePlayerMaxHeart>},
    {0xa9bfdafe, Factory::make<query::CompareGameDataFloat>},
    {0xae2fac6a, Factory::make<query::CheckPlayerHellType>},
    {0xaf4d3b5c, Factory::make<query::ComparePlayerMaxStamina>},
    {0xafa27c1b, Factory::make<query::CheckRoad>},
    {0xb1af10f2, Factory::make<query::CheckExtraEnergyOfPlayer>},
    {0xb3b3e50c, Factory::make<query::CheckAreaTransition>},
    {0xb44f3c12, Factory::make<query::HasArmorDye>},
    {0xb4506d9a, Factory::make<query::HasItemDyeSpecifiedColor>},
    {0xb55dd6c1, Factory::make<query::IsAwakened>},
    {0xb62b2566, Factory::make<query::CheckItemShopDecide>},
    {0xb70beba6, Factory::make<query::CheckTypeOfWildHorseAssociated>},
    {0xb9a274e8, Factory::make<query::CheckElapsedTimeOfMiniGame>},
    {0xba1e274f, Factory::make<query::WhatDungeonType>},
    {0xc35a0cd9, Factory::make<query::CheckTimeType>},
    {0xc3bfae2a, Factory::make<query::CheckReceiveTerrorLevel>},
    {0xc4e7d5df, Factory::make<query::HasSpecificArmorSeries>},
    {0xc4f7316f, Factory::make<query::CheckCookResultStatus>},
    {0xc59e26da, Factory::make<query::CompareGameDataTime>},
    {0xc6bd2d35, Factory::make<query::IsItemInStock>},
    {0xc7641ec2, Factory::make<query::CheckMiniGameTimeOver>},
    {0xc7b0c4b4, Factory::make<query::HasPorchItemByCategory>},
    {0xc9aa53ff, Factory::make<query::HasPouchItemByPouchCategory>},
    {0xcb187157, Factory::make<query::IsSoldOut>},
    {0xcc8c5c6e, Factory::make<query::IsHorseFamiliarityPassedAlready>},
    {0xcca94665, Factory::make<query::CheckContainerItem>},
    {0xcfb8756a, Factory::make<query::CheckAddPorchItem>},
    {0xcfd37d18, Factory::make<query::CheckResultOfNPCConflict>},
    {0xd052b6b8, Factory::make<query::CheckManufactResult>},
    {0xd1070742, Factory::make<query::CheckActorAction14_2>},
    {0xd23283af, Factory::make<query::Check100EnemyActiveTiming>},
    {0xd95342d1, Factory::make<query::IsIgnitionByArrowFire>},
    {0xda2a902d, Factory::make<query::CheckFadeState>},
    {0xdaeced1e, Factory::make<query::IsOnEnterDungeonFlag>},
    {0xdc704842, Factory::make<query::CheckItemShopSelect>},
    {0xdf1b5246, Factory::make<query::HasSetItem>},
    {0xe17fc869, Factory::make<query::CheckOwnedHorseFamiliarity>},
    {0xe29fe0ca, Factory::make<query::CheckExistArrow>},
    {0xe60c37bf, Factory::make<query::RandomChoice3>},
    {0xe6a386e7, Factory::make<query::CheckPlayerPullSwordFailEnd>},
    {0xe6c6fbc5, Factory::make<query::IsCurrentMainFieldDungeonStage>},
    {0xe78234da, Factory::make<query::EnemyDieCheck>},
    {0xeb965330, Factory::make<query::CheckFlag>},
    {0xec7529d4, Factory::make<query::CheckItemShopSelectBuy>},
    {0xecfe1e50, Factory::make<query::IsNeedEquipWeapon>},
    {0xed049add, Factory::make<query::IsArriveAnchorForRain>},
    {0xeda9870b, Factory::make<query::CheckTerrorLevel>},
    {0xf0074ef3, Factory::make<query::IsOnInstEventFlag>},
    {0xf39c6c52, Factory::make<query::CheckWeaponVacancyItem>},
    {0xf3bfbc24, Factory::make<ksys::act::ai::CheckEventCancel>},
    {0xf445bb27, Factory::make<query::CheckStage>},
    {0xf44bfc07, Factory::make<query::CheckPlayerState>},
    {0xf4db0067, Factory::make<query::IsCurrentMainFieldStage>},
    {0xf5e56bc8, Factory::make<query::CheckDieCnt>},
    {0xf601bdf7, Factory::make<query::CheckLastDamageAttacker>},
    {0xf7cc0cc6, Factory::make<query::CheckPlayerRideHorse>},
    {0xf7dce469, Factory::make<query::CanMarkMapPin>},
    {0xfaad5f7c, Factory::make<query::IsTerrorDisappeared>},
    {0xfdb77b22, Factory::make<query::CheckActorAction13>},
    {0xfe30a6c1, Factory::make<query::EnemyRestLifeRate>},
};

void initQueryFactories() {
    ksys::act::ai::Queries::setFactories(std::size(sQueryFactories), sQueryFactories);
}

}  // namespace uking
