#pragma once

enum hkpCollidableQualityType : int {
    HK_COLLIDABLE_QUALITY_INVALID = -1,
    HK_COLLIDABLE_QUALITY_FIXED = 0,
    HK_COLLIDABLE_QUALITY_KEYFRAMED,
    HK_COLLIDABLE_QUALITY_DEBRIS,
    HK_COLLIDABLE_QUALITY_DEBRIS_SIMPLE_TOI,
    HK_COLLIDABLE_QUALITY_MOVING,
    HK_COLLIDABLE_QUALITY_CRITICAL,
    HK_COLLIDABLE_QUALITY_BULLET,
    HK_COLLIDABLE_QUALITY_USER,
    HK_COLLIDABLE_QUALITY_CHARACTER,
    HK_COLLIDABLE_QUALITY_KEYFRAMED_REPORTING,
    HK_COLLIDABLE_QUALITY_MAX
};
